### ISSUE TITLE
target 'E' in function create_image

### ISSUE THREAD

**Issue by TranThanh96** [NVlabs/few_shot_gaze#15]
can u explain in detail the meaning of 'E'. what direction should I follow when the character 'E' appears on the screen?

**Comment by shalinidemello** [comment]
When you conduct the calibration expriement, the user is shown the letter 'E' oriented in 4 different directions chosen randomly on the screen. In order to force the user to look at the target 'E' shown on the screen we ask the user to press the "up", "down", "left", "right" arrows that corresponds to the direction of the letter "E" shown on-screen. If they press the wrong key another randomly oriented target is shown at the same location on the screen, until the user pays attention and presses the correct arrow key.
