### ISSUE TITLE
result without fine-tune model for new person

### ISSUE THREAD

**Issue by TranThanh96** [NVlabs/few_shot_gaze#16]
Can you provide the result without fine-tuning the model with a new person?

**Comment by shalinidemello** [comment]
You can comment out this line in the code: https://github.com/NVlabs/few_shot_gaze/blob/master/demo/run_demo.py#L114

Also, note that in order to correctly compute the intersection of the gaze ray with your monitor and the point-of-regard on the screen, you need to calibrate the orientation and the position (in metric space) of the upper-left corner of your monitor with respect to your camera as described in step 2b of https://github.com/NVlabs/few_shot_gaze/blob/master/demo/README.md.
